version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-ocr-bot
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src  # Монтируем директорию с исходным кодом
      - ./logs:/app/logs  # Директория для логов
    command: uv run /app/src/bot/__main__.py  # Запускаем модуль напрямую

volumes:
  logs: